// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atmdflflunqujnpkyiev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bWRmbGZsdW5xdWpucGt5aWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjkzNTksImV4cCI6MjA2NjcwNTM1OX0.UijZXfh_yZTVt_q8ynS4P4OamcSvIh0eoIJpy1sBtHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);